//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 08:22:35 AM EET 
//


package com.electriccloud.export.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.electriccloud.export.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.electriccloud.export.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExportedData }
     * 
     */
    public ExportedData createExportedData() {
        return new ExportedData();
    }

    /**
     * Create an instance of {@link AbstractProject }
     * 
     */
    public AbstractProject createAbstractProject() {
        return new AbstractProject();
    }

    /**
     * Create an instance of {@link FormalParameter }
     * 
     */
    public FormalParameter createFormalParameter() {
        return new FormalParameter();
    }

    /**
     * Create an instance of {@link Procedure }
     * 
     */
    public Procedure createProcedure() {
        return new Procedure();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link PropertySheet }
     * 
     */
    public PropertySheet createPropertySheet() {
        return new PropertySheet();
    }

}
