//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 08:59:05 AM EET 
//


package com.electriccloud.plugin.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.electriccloud.plugin.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Key_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "key");
    private final static QName _Version_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "version");
    private final static QName _Label_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "label");
    private final static QName _Description_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "description");
    private final static QName _Help_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "help");
    private final static QName _Configure_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "configure");
    private final static QName _Vendor_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "vendor");
    private final static QName _Author_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "author");
    private final static QName _AuthorUrl_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "authorUrl");
    private final static QName _Category_QNAME = new QName("http://electric-cloud.com/commander/3.6/plugins", "category");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.electriccloud.plugin.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Plugin }
     * 
     */
    public Plugin createPlugin() {
        return new Plugin();
    }

    /**
     * Create an instance of {@link CommanderVersion }
     * 
     */
    public CommanderVersion createCommanderVersion() {
        return new CommanderVersion();
    }

    /**
     * Create an instance of {@link Depends }
     * 
     */
    public Depends createDepends() {
        return new Depends();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link CustomType }
     * 
     */
    public CustomType createCustomType() {
        return new CustomType();
    }

    /**
     * Create an instance of {@link Executables }
     * 
     */
    public Executables createExecutables() {
        return new Executables();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link Page }
     * 
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "key")
    public JAXBElement<String> createKey(String value) {
        return new JAXBElement<String>(_Key_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "help")
    public JAXBElement<String> createHelp(String value) {
        return new JAXBElement<String>(_Help_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "configure")
    public JAXBElement<String> createConfigure(String value) {
        return new JAXBElement<String>(_Configure_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "vendor")
    public JAXBElement<String> createVendor(String value) {
        return new JAXBElement<String>(_Vendor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "authorUrl")
    public JAXBElement<String> createAuthorUrl(String value) {
        return new JAXBElement<String>(_AuthorUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://electric-cloud.com/commander/3.6/plugins", name = "category")
    public JAXBElement<String> createCategory(String value) {
        return new JAXBElement<String>(_Category_QNAME, String.class, null, value);
    }

}
