//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 08:59:05 AM EET 
//


package com.electriccloud.plugin.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}key"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}version"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}label" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}description" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}help" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}configure" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}vendor" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}author" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}authorUrl" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}category" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}commander-version" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}depends" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}components" minOccurs="0"/&gt;
 *         &lt;element ref="{http://electric-cloud.com/commander/3.6/plugins}executables" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "key",
    "version",
    "label",
    "description",
    "help",
    "configure",
    "vendor",
    "author",
    "authorUrl",
    "category",
    "commanderVersion",
    "depends",
    "components",
    "executables"
})
@XmlRootElement(name = "plugin")
public class Plugin {

    @XmlElement(required = true)
    protected String key;
    @XmlElement(required = true)
    protected String version;
    protected String label;
    protected String description;
    protected String help;
    protected String configure;
    protected String vendor;
    protected String author;
    protected String authorUrl;
    protected String category;
    @XmlElement(name = "commander-version")
    protected CommanderVersion commanderVersion;
    protected List<Depends> depends;
    protected Components components;
    protected Executables executables;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the configure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigure() {
        return configure;
    }

    /**
     * Sets the value of the configure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigure(String value) {
        this.configure = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the authorUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorUrl() {
        return authorUrl;
    }

    /**
     * Sets the value of the authorUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorUrl(String value) {
        this.authorUrl = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the commanderVersion property.
     * 
     * @return
     *     possible object is
     *     {@link CommanderVersion }
     *     
     */
    public CommanderVersion getCommanderVersion() {
        return commanderVersion;
    }

    /**
     * Sets the value of the commanderVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommanderVersion }
     *     
     */
    public void setCommanderVersion(CommanderVersion value) {
        this.commanderVersion = value;
    }

    /**
     * Gets the value of the depends property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the depends property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepends().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Depends }
     * 
     * 
     */
    public List<Depends> getDepends() {
        if (depends == null) {
            depends = new ArrayList<Depends>();
        }
        return this.depends;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link Components }
     *     
     */
    public Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link Components }
     *     
     */
    public void setComponents(Components value) {
        this.components = value;
    }

    /**
     * Gets the value of the executables property.
     * 
     * @return
     *     possible object is
     *     {@link Executables }
     *     
     */
    public Executables getExecutables() {
        return executables;
    }

    /**
     * Sets the value of the executables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Executables }
     *     
     */
    public void setExecutables(Executables value) {
        this.executables = value;
    }

}
